apiVersion: v2
name: questdb
version: 1.0.18
appVersion: 9.3.0
description: Run QuestDB on Kubernetes via Helm
icon: https://questdb.com/img/favicon.png
home: https://questdb.com
sources:
  - https://github.com/questdb/questdb-kubernetes/
type: application
keywords:
  - questdb
  - database
  - timeseries
  - sql
maintainers:
- email: containers@questdb.com
  name: QuestDB Team
