apiVersion: v2
name: questdb
version: 0.13.0
appVersion: 6.1.1
description: Run QuestDB on Kubernetes via Helm
icon: https://questdb.io/img/favicon.png
home: https://questdb.io
sources:
  - https://github.com/questdb/questdb-kubernetes
type: application
keywords:
  - questdb
  - database
  - timeseries
  - sql
maintainers:
- email: containers@questdb.io
  name: QuestDB Team

# Chart.yaml reference:
# https://helm.sh/docs/topics/charts/#the-chart-yaml-file
